/*
 * e2e/oa/levels.check.ts — GENERATED from catalog.json. Do not edit by hand.
 *
 * Every non-"(omit)" level of every factor, assigned to the field it configures. The file
 * is never imported and never runs: it exists so that `pnpm exec tsc -p e2e --noEmit`
 * rejects a level expression whose shape does not match the plugin's config type. See
 * e2e/oa/CLAUDE.md §3.7 for how to regenerate it.
 */
import type {
  PresetStandardConfig,
  DataSyncConfig,
  I18nConfig,
  PerfToolsConfig,
  PortfolioConfig,
  ResourceConfig,
  TrackingConfig,
} from "stargantt";

/* The fixtures catalog.json emits at the top of every boot. Declared, not defined: this
   file checks the level expressions, not the fixtures they close over. */
declare const OA_RUN_DATASET: any;
declare const OA_C_DATA_SOURCE: any;
declare const OA_C_GQL_FETCH: any;
declare const OA_C_LAZY_SOURCE: any;
declare const OA_C_REALTIME_TRANSPORT: any;

const data_store_messages_l1: Pick<NonNullable<PresetStandardConfig["dataStore"]>, "messages"> = { messages: {} };
const data_store_messages_l2: Pick<NonNullable<PresetStandardConfig["dataStore"]>, "messages"> = { messages: { taskMove: "OA Move" } };
const data_store_customFields_l1: Pick<NonNullable<PresetStandardConfig["dataStore"]>, "customFields"> = { customFields: { fields: [] } };
const data_store_customFields_l2: Pick<NonNullable<PresetStandardConfig["dataStore"]>, "customFields"> = { customFields: { fields: [{ key: "oaText", label: "OA Text" }, { key: "oaNum", type: "number", label: "OA Num", width: 80 }] } };
const task_bars_label_l1: Pick<NonNullable<PresetStandardConfig["taskBars"]>, "label"> = { label: (task) => task.name };
const task_bars_label_l2: Pick<NonNullable<PresetStandardConfig["taskBars"]>, "label"> = { label: { text: (task) => (task.type === "summary" ? undefined : task.name), placement: "inside" } };
const task_bars_messages_l1: Pick<NonNullable<PresetStandardConfig["taskBars"]>, "messages"> = { messages: {} };
const task_bars_messages_l2: Pick<NonNullable<PresetStandardConfig["taskBars"]>, "messages"> = { messages: { empty: "OA no tasks" } };
const task_bars_labelBackdrop_l1: Pick<NonNullable<PresetStandardConfig["taskBars"]>, "labelBackdrop"> = { labelBackdrop: false };
const task_bars_labelBackdrop_l2: Pick<NonNullable<PresetStandardConfig["taskBars"]>, "labelBackdrop"> = { labelBackdrop: { color: "#fffbe6", padding: 3, radius: 4 } };
const task_bars_durationLabel_l1: Pick<NonNullable<PresetStandardConfig["taskBars"]>, "durationLabel"> = { durationLabel: true };
const task_bars_durationLabel_l2: Pick<NonNullable<PresetStandardConfig["taskBars"]>, "durationLabel"> = { durationLabel: { placement: "left" } };
const task_bars_progressLabel_l1: Pick<NonNullable<PresetStandardConfig["taskBars"]>, "progressLabel"> = { progressLabel: true };
const task_bars_progressLabel_l2: Pick<NonNullable<PresetStandardConfig["taskBars"]>, "progressLabel"> = { progressLabel: { placement: "right" } };
const task_bars_renderBar_l1: Pick<NonNullable<PresetStandardConfig["taskBars"]>, "renderBar"> = { renderBar: (g, a) => { a.defaultPaint(); g.strokeStyle = "#1a365d"; g.strokeRect(a.box.x + 0.5, a.box.y + 0.5, Math.max(1, a.box.width - 1), Math.max(1, a.box.height - 1)); } };
const task_bars_renderBar_l2: Pick<NonNullable<PresetStandardConfig["taskBars"]>, "renderBar"> = { renderBar: (g, a) => { g.strokeStyle = "#4a5568"; g.strokeRect(a.box.x + 0.5, a.box.y + 0.5, Math.max(1, a.box.width - 1), Math.max(1, a.box.height - 1)); } };
const task_bars_milestoneShape_l1: Pick<NonNullable<PresetStandardConfig["taskBars"]>, "milestoneShape"> = { milestoneShape: "star" };
const task_bars_milestoneShape_l2: Pick<NonNullable<PresetStandardConfig["taskBars"]>, "milestoneShape"> = { milestoneShape: (task) => (task.type === "milestone" ? "triangle" : undefined) };
const task_bars_patternFill_l1: Pick<NonNullable<PresetStandardConfig["taskBars"]>, "patternFill"> = { patternFill: true };
const task_bars_patternFill_l2: Pick<NonNullable<PresetStandardConfig["taskBars"]>, "patternFill"> = { patternFill: (task) => (task.type === "summary" ? "dots" : "diagonal") };
const task_bars_barRadius_l1: Pick<NonNullable<PresetStandardConfig["taskBars"]>, "barRadius"> = { barRadius: 0 };
const task_bars_barRadius_l2: Pick<NonNullable<PresetStandardConfig["taskBars"]>, "barRadius"> = { barRadius: 10 };
const task_bars_barIcons_l1: Pick<NonNullable<PresetStandardConfig["taskBars"]>, "barIcons"> = { barIcons: (task) => (task.type ? undefined : { left: "!", right: "*" }) };
const task_bars_barIcons_l2: Pick<NonNullable<PresetStandardConfig["taskBars"]>, "barIcons"> = { barIcons: () => undefined };
const task_bars_avatar_l1: Pick<NonNullable<PresetStandardConfig["taskBars"]>, "avatar"> = { avatar: (task) => (task.id === "oa-a" ? { initials: "OA", color: "#805ad5" } : undefined) };
const task_bars_avatar_l2: Pick<NonNullable<PresetStandardConfig["taskBars"]>, "avatar"> = { avatar: () => undefined };
const task_bars_collapsedSummary_l1: Pick<NonNullable<PresetStandardConfig["taskBars"]>, "collapsedSummary"> = { collapsedSummary: "hidden" };
const task_bars_collapsedSummary_l2: Pick<NonNullable<PresetStandardConfig["taskBars"]>, "collapsedSummary"> = { collapsedSummary: "split" };
const task_bars_expandedHitArea_l1: Pick<NonNullable<PresetStandardConfig["taskBars"]>, "expandedHitArea"> = { expandedHitArea: true };
const task_bars_expandedHitArea_l2: Pick<NonNullable<PresetStandardConfig["taskBars"]>, "expandedHitArea"> = { expandedHitArea: false };
const tree_grid_messages_l1: Pick<NonNullable<PresetStandardConfig["treeGrid"]>, "messages"> = { messages: {} };
const tree_grid_messages_l2: Pick<NonNullable<PresetStandardConfig["treeGrid"]>, "messages"> = { messages: { nameColumn: "OA Task" } };
const tree_grid_rowHeight_l1: Pick<NonNullable<PresetStandardConfig["treeGrid"]>, "rowHeight"> = { rowHeight: 20 };
const tree_grid_rowHeight_l2: Pick<NonNullable<PresetStandardConfig["treeGrid"]>, "rowHeight"> = { rowHeight: 48 };
const tree_grid_paneWidth_l1: Pick<NonNullable<PresetStandardConfig["treeGrid"]>, "paneWidth"> = { paneWidth: 240 };
const tree_grid_paneWidth_l2: Pick<NonNullable<PresetStandardConfig["treeGrid"]>, "paneWidth"> = { paneWidth: 400 };
const tree_grid_indent_l1: Pick<NonNullable<PresetStandardConfig["treeGrid"]>, "indent"> = { indent: 0 };
const tree_grid_indent_l2: Pick<NonNullable<PresetStandardConfig["treeGrid"]>, "indent"> = { indent: 32 };
const tree_grid_readOnly_l1: Pick<NonNullable<PresetStandardConfig["treeGrid"]>, "readOnly"> = { readOnly: true };
const tree_grid_readOnly_l2: Pick<NonNullable<PresetStandardConfig["treeGrid"]>, "readOnly"> = { readOnly: false };
const tree_grid_columns_l1: Pick<NonNullable<PresetStandardConfig["treeGrid"]>, "columns"> = { columns: [] };
const tree_grid_columns_l2: Pick<NonNullable<PresetStandardConfig["treeGrid"]>, "columns"> = { columns: [{ id: "oa-name", header: "Task", width: 220, render: (el, task) => { el.textContent = task.name; }, getValue: (task) => task.name, compare: (a, b) => (a.name < b.name ? -1 : a.name > b.name ? 1 : 0) }] };
const tree_grid_formatDate_l1: Pick<NonNullable<PresetStandardConfig["treeGrid"]>, "formatDate"> = { formatDate: (t) => new Date(t).toISOString().slice(5, 10) };
const tree_grid_formatDate_l2: Pick<NonNullable<PresetStandardConfig["treeGrid"]>, "formatDate"> = { formatDate: () => "" };
const tree_grid_formatProgress_l1: Pick<NonNullable<PresetStandardConfig["treeGrid"]>, "formatProgress"> = { formatProgress: (p) => (p * 100).toFixed(1) + " pct" };
const tree_grid_formatProgress_l2: Pick<NonNullable<PresetStandardConfig["treeGrid"]>, "formatProgress"> = { formatProgress: () => "" };
const tree_grid_columnLayout_l1: Pick<NonNullable<PresetStandardConfig["treeGrid"]>, "columnLayout"> = { columnLayout: { hidden: ["progress"] } };
const tree_grid_columnLayout_l2: Pick<NonNullable<PresetStandardConfig["treeGrid"]>, "columnLayout"> = { columnLayout: { order: ["end", "start", "name"] } };
const tree_grid_cellRenderers_l1: Pick<NonNullable<PresetStandardConfig["treeGrid"]>, "cellRenderers"> = { cellRenderers: {} };
const tree_grid_cellRenderers_l2: Pick<NonNullable<PresetStandardConfig["treeGrid"]>, "cellRenderers"> = { cellRenderers: { name: (el, task) => { el.textContent = "* " + task.name; } } };
const tree_grid_rowClass_l1: Pick<NonNullable<PresetStandardConfig["treeGrid"]>, "rowClass"> = { rowClass: (task) => (task.type === "summary" ? "oa-row-summary" : undefined) };
const tree_grid_rowClass_l2: Pick<NonNullable<PresetStandardConfig["treeGrid"]>, "rowClass"> = { rowClass: () => undefined };
const tree_grid_wbs_l1: Pick<NonNullable<PresetStandardConfig["treeGrid"]>, "wbs"> = { wbs: true };
const tree_grid_wbs_l2: Pick<NonNullable<PresetStandardConfig["treeGrid"]>, "wbs"> = { wbs: false };
const tree_grid_collapsedBadge_l1: Pick<NonNullable<PresetStandardConfig["treeGrid"]>, "collapsedBadge"> = { collapsedBadge: true };
const tree_grid_collapsedBadge_l2: Pick<NonNullable<PresetStandardConfig["treeGrid"]>, "collapsedBadge"> = { collapsedBadge: false };
const tree_grid_outlineEditing_l1: Pick<NonNullable<PresetStandardConfig["treeGrid"]>, "outlineEditing"> = { outlineEditing: true };
const tree_grid_outlineEditing_l2: Pick<NonNullable<PresetStandardConfig["treeGrid"]>, "outlineEditing"> = { outlineEditing: false };
const tree_grid_collation_l1: Pick<NonNullable<PresetStandardConfig["treeGrid"]>, "collation"> = { collation: true };
const tree_grid_collation_l2: Pick<NonNullable<PresetStandardConfig["treeGrid"]>, "collation"> = { collation: { locales: "en", options: { numeric: true, sensitivity: "base" } } };
const tree_grid_taskFields_l1: Pick<NonNullable<PresetStandardConfig["treeGrid"]>, "taskFields"> = { taskFields: {} };
const tree_grid_taskFields_l2: Pick<NonNullable<PresetStandardConfig["treeGrid"]>, "taskFields"> = { taskFields: { columns: ["id", "status", "priority", "deadline"], durationUnit: "hours", idNumbering: { prefix: "T-", start: 1, minDigits: 3 }, showAssigneeAvatars: false } };
const tree_grid_conditionalFormat_l1: Pick<NonNullable<PresetStandardConfig["treeGrid"]>, "conditionalFormat"> = { conditionalFormat: {} };
const tree_grid_conditionalFormat_l2: Pick<NonNullable<PresetStandardConfig["treeGrid"]>, "conditionalFormat"> = { conditionalFormat: { rules: [{ when: { field: "progress", op: "gte", value: 0.5 }, style: { color: "#2f855a" }, legend: "Half done" }], overdue: true, progress: true, legend: true } };
const view_scroll_l1: Pick<NonNullable<PresetStandardConfig["view"]>, "scroll"> = { scroll: { scrollbar: false } };
const view_scroll_l2: Pick<NonNullable<PresetStandardConfig["view"]>, "scroll"> = { scroll: { wheelSpeedFactor: 2.5 } };
const view_direction_l1: Pick<NonNullable<PresetStandardConfig["view"]>, "direction"> = { direction: "ltr" };
const view_direction_l2: Pick<NonNullable<PresetStandardConfig["view"]>, "direction"> = { direction: "rtl" };
const view_progressive_l1: Pick<NonNullable<PresetStandardConfig["view"]>, "progressive"> = { progressive: true };
const view_progressive_l2: Pick<NonNullable<PresetStandardConfig["view"]>, "progressive"> = { progressive: false };
const view_dirtyRegions_l1: Pick<NonNullable<PresetStandardConfig["view"]>, "dirtyRegions"> = { dirtyRegions: true };
const view_dirtyRegions_l2: Pick<NonNullable<PresetStandardConfig["view"]>, "dirtyRegions"> = { dirtyRegions: false };
const view_prefetch_l1: Pick<NonNullable<PresetStandardConfig["view"]>, "prefetch"> = { prefetch: true };
const view_prefetch_l2: Pick<NonNullable<PresetStandardConfig["view"]>, "prefetch"> = { prefetch: false };
const view_panes_l1: Pick<NonNullable<PresetStandardConfig["view"]>, "panes"> = { panes: { initialViewMode: "gantt" } };
const view_panes_l2: Pick<NonNullable<PresetStandardConfig["view"]>, "panes"> = { panes: { initialViewMode: "grid" } };
const view_theme_l1: Pick<NonNullable<PresetStandardConfig["view"]>, "theme"> = { theme: { preset: "high-contrast" } };
const view_theme_l2: Pick<NonNullable<PresetStandardConfig["view"]>, "theme"> = { theme: { colorScheme: "dark", diagnostics: false } };
const view_timeline_l1: Pick<NonNullable<PresetStandardConfig["view"]>, "timeline"> = { timeline: { origin: Date.UTC(2026, 7, 5), autoExtendOrigin: true } };
const view_timeline_l2: Pick<NonNullable<PresetStandardConfig["view"]>, "timeline"> = { timeline: { initialZoom: "week", firstDayOfWeek: 0, headerRowRatio: 0.4, displayTimeZone: "Asia/Tokyo" } };
const view_gridLines_l1: Pick<NonNullable<PresetStandardConfig["view"]>, "gridLines"> = { gridLines: { vertical: "both", horizontal: true, rowHover: true } };
const view_gridLines_l2: Pick<NonNullable<PresetStandardConfig["view"]>, "gridLines"> = { gridLines: { vertical: "none", rowStripes: false, nonWorkingDays: { weekend: [0, 6] }, zones: [{ start: Date.UTC(2026, 7, 8), end: Date.UTC(2026, 7, 10) }] } };
const view_todayLine_l1: Pick<NonNullable<PresetStandardConfig["view"]>, "todayLine"> = { todayLine: false };
const view_todayLine_l2: Pick<NonNullable<PresetStandardConfig["view"]>, "todayLine"> = { todayLine: { statusDate: "2026-08-09" } };
const data_sync_sources_l1: Pick<DataSyncConfig, "sources"> = { sources: {} };
const data_sync_sources_l2: Pick<DataSyncConfig, "sources"> = { sources: { "oa-src": OA_C_DATA_SOURCE } };
const data_sync_active_l1: Pick<DataSyncConfig, "active"> = { active: "oa-src" };
const data_sync_active_l2: Pick<DataSyncConfig, "active"> = { active: "oa-missing-src" };
const data_sync_autoLoad_l1: Pick<DataSyncConfig, "autoLoad"> = { autoLoad: true };
const data_sync_autoLoad_l2: Pick<DataSyncConfig, "autoLoad"> = { autoLoad: false };
const data_sync_rollbackOnError_l1: Pick<DataSyncConfig, "rollbackOnError"> = { rollbackOnError: true };
const data_sync_rollbackOnError_l2: Pick<DataSyncConfig, "rollbackOnError"> = { rollbackOnError: false };
const data_sync_followFilter_l1: Pick<DataSyncConfig, "followFilter"> = { followFilter: true };
const data_sync_followFilter_l2: Pick<DataSyncConfig, "followFilter"> = { followFilter: false };
const data_sync_followFilterDebounceMs_l1: Pick<DataSyncConfig, "followFilterDebounceMs"> = { followFilterDebounceMs: 0 };
const data_sync_followFilterDebounceMs_l2: Pick<DataSyncConfig, "followFilterDebounceMs"> = { followFilterDebounceMs: 5000 };
const data_sync_graphql_l1: Pick<DataSyncConfig, "graphql"> = { graphql: { name: "oa-gql" } };
const data_sync_graphql_l2: Pick<DataSyncConfig, "graphql"> = { graphql: { name: "oa-gql", url: "https://oa.invalid/graphql", operations: { load: "query { tasks { id name start end } }" }, fetch: OA_C_GQL_FETCH } };
const data_sync_lazyLoad_l1: Pick<DataSyncConfig, "lazyLoad"> = { lazyLoad: { sources: { "oa-lazy": OA_C_LAZY_SOURCE }, active: "oa-lazy", autoLoad: true, pageSize: 2 } };
const data_sync_lazyLoad_l2: Pick<DataSyncConfig, "lazyLoad"> = { lazyLoad: { sources: { "oa-lazy": OA_C_LAZY_SOURCE }, active: "oa-lazy", followViewport: true, prefetchPages: 0 } };
const data_sync_offline_l1: Pick<DataSyncConfig, "offline"> = { offline: { databaseName: "oa-offline-db", documentKey: "oa-doc" } };
const data_sync_offline_l2: Pick<DataSyncConfig, "offline"> = { offline: { autoSave: true, autoSaveDebounceMs: 0, registerSource: false } };
const data_sync_realtime_l1: Pick<DataSyncConfig, "realtime"> = { realtime: { transports: { "oa-rt": OA_C_REALTIME_TRANSPORT }, connect: "oa-rt" } };
const data_sync_realtime_l2: Pick<DataSyncConfig, "realtime"> = { realtime: { transports: { "oa-rt": OA_C_REALTIME_TRANSPORT }, connect: "oa-rt", autoReconnect: false, resyncViaDataSource: false } };
const i18n_locale_l1: Pick<I18nConfig, "locale"> = { locale: "ja-JP" };
const i18n_locale_l2: Pick<I18nConfig, "locale"> = { locale: "fr" };
const i18n_fallbacks_l1: Pick<I18nConfig, "fallbacks"> = { fallbacks: [] };
const i18n_fallbacks_l2: Pick<I18nConfig, "fallbacks"> = { fallbacks: ["ja", "en"] };
const i18n_translations_l1: Pick<I18nConfig, "translations"> = { translations: {} };
const i18n_translations_l2: Pick<I18nConfig, "translations"> = { translations: { ja: { "oa.greeting": "Konnichiwa" } } };
const perf_tools_overlay_l1: Pick<PerfToolsConfig, "overlay"> = { overlay: true };
const perf_tools_overlay_l2: Pick<PerfToolsConfig, "overlay"> = { overlay: false };
const perf_tools_sparkline_l1: Pick<PerfToolsConfig, "sparkline"> = { sparkline: true };
const perf_tools_sparkline_l2: Pick<PerfToolsConfig, "sparkline"> = { sparkline: false };
const perf_tools_position_l1: Pick<PerfToolsConfig, "position"> = { position: "bottom-left" };
const perf_tools_position_l2: Pick<PerfToolsConfig, "position"> = { position: "top-left" };
const perf_tools_budgetMs_l1: Pick<PerfToolsConfig, "budgetMs"> = { budgetMs: 1 };
const perf_tools_budgetMs_l2: Pick<PerfToolsConfig, "budgetMs"> = { budgetMs: 100 };
const perf_tools_windowSize_l1: Pick<PerfToolsConfig, "windowSize"> = { windowSize: 1 };
const perf_tools_windowSize_l2: Pick<PerfToolsConfig, "windowSize"> = { windowSize: 600 };
const perf_tools_performanceMarks_l1: Pick<PerfToolsConfig, "performanceMarks"> = { performanceMarks: true };
const perf_tools_performanceMarks_l2: Pick<PerfToolsConfig, "performanceMarks"> = { performanceMarks: false };
const perf_tools_messages_l1: Pick<PerfToolsConfig, "messages"> = { messages: {} };
const perf_tools_messages_l2: Pick<PerfToolsConfig, "messages"> = { messages: { readout: (stats) => "OA " + Math.round(stats.fps) + " fps / " + stats.frames + " frames" } };
const export_messages_l1: Pick<NonNullable<PresetStandardConfig["export"]>, "messages"> = { messages: {} };
const export_messages_l2: Pick<NonNullable<PresetStandardConfig["export"]>, "messages"> = { messages: { pageNumber: (info) => "p. " + info.page + "/" + info.pages } };
const export_image_l1: Pick<NonNullable<PresetStandardConfig["export"]>, "image"> = { image: { background: "#ffffff", pixelRatio: 1 } };
const export_image_l2: Pick<NonNullable<PresetStandardConfig["export"]>, "image"> = { image: { range: "full", pixelRatio: 2 } };
const export_print_l1: Pick<NonNullable<PresetStandardConfig["export"]>, "print"> = { print: { paper: "letter", orientation: "portrait" } };
const export_print_l2: Pick<NonNullable<PresetStandardConfig["export"]>, "print"> = { print: { scale: 50, columns: ["name", "start", "end"], legend: false, header: { center: "OA Print" } } };
const export_importExport_l1: Pick<NonNullable<PresetStandardConfig["export"]>, "importExport"> = { importExport: { csvDelimiter: ";" } };
const export_importExport_l2: Pick<NonNullable<PresetStandardConfig["export"]>, "importExport"> = { importExport: { csvDelimiter: "\t" } };
const export_excel_l1: Pick<NonNullable<PresetStandardConfig["export"]>, "excel"> = { excel: { sheetName: "OA Sheet" } };
const export_excel_l2: Pick<NonNullable<PresetStandardConfig["export"]>, "excel"> = { excel: { sheetName: "OA[]:*?" } };
const export_viewerEmbed_l1: Pick<NonNullable<PresetStandardConfig["export"]>, "viewerEmbed"> = { viewerEmbed: { readOnly: true, snapshotParam: "oa-snap" } };
const export_viewerEmbed_l2: Pick<NonNullable<PresetStandardConfig["export"]>, "viewerEmbed"> = { viewerEmbed: { embed: true, readOnly: false, autoRestore: true } };
const a11y_label_l1: Pick<NonNullable<PresetStandardConfig["a11y"]>, "label"> = { label: "OA Chart" };
const a11y_label_l2: Pick<NonNullable<PresetStandardConfig["a11y"]>, "label"> = { label: "   " };
const a11y_messages_l1: Pick<NonNullable<PresetStandardConfig["a11y"]>, "messages"> = { messages: {} };
const a11y_messages_l2: Pick<NonNullable<PresetStandardConfig["a11y"]>, "messages"> = { messages: { rowText: (parts) => parts.name + " (" + Math.round((parts.progress ?? 0) * 100) + "%)" } };
const a11y_syncSelection_l1: Pick<NonNullable<PresetStandardConfig["a11y"]>, "syncSelection"> = { syncSelection: true };
const a11y_syncSelection_l2: Pick<NonNullable<PresetStandardConfig["a11y"]>, "syncSelection"> = { syncSelection: false };
const a11y_describeDependencies_l1: Pick<NonNullable<PresetStandardConfig["a11y"]>, "describeDependencies"> = { describeDependencies: true };
const a11y_describeDependencies_l2: Pick<NonNullable<PresetStandardConfig["a11y"]>, "describeDependencies"> = { describeDependencies: false };
const a11y_shortcutHelp_l1: Pick<NonNullable<PresetStandardConfig["a11y"]>, "shortcutHelp"> = { shortcutHelp: true };
const a11y_shortcutHelp_l2: Pick<NonNullable<PresetStandardConfig["a11y"]>, "shortcutHelp"> = { shortcutHelp: false };
const a11y_zoomKeys_l1: Pick<NonNullable<PresetStandardConfig["a11y"]>, "zoomKeys"> = { zoomKeys: true };
const a11y_zoomKeys_l2: Pick<NonNullable<PresetStandardConfig["a11y"]>, "zoomKeys"> = { zoomKeys: false };
const a11y_summaryTable_l1: Pick<NonNullable<PresetStandardConfig["a11y"]>, "summaryTable"> = { summaryTable: true };
const a11y_summaryTable_l2: Pick<NonNullable<PresetStandardConfig["a11y"]>, "summaryTable"> = { summaryTable: false };
const interaction_selection_l1: Pick<NonNullable<PresetStandardConfig["interaction"]>, "selection"> = { selection: { mode: "multi", shortcuts: { selectAll: true, clearOnEscape: true, deleteSelected: true } } };
const interaction_selection_l2: Pick<NonNullable<PresetStandardConfig["interaction"]>, "selection"> = { selection: { mode: "none", revealSelected: false } };
const interaction_dragEdit_l1: Pick<NonNullable<PresetStandardConfig["interaction"]>, "dragEdit"> = { dragEdit: { enabled: false } };
const interaction_dragEdit_l2: Pick<NonNullable<PresetStandardConfig["interaction"]>, "dragEdit"> = { dragEdit: { liveUpdate: true, dragTooltip: true, rowDrag: true, autoScroll: true, dependencyPreview: true, frameSync: true, minDuration: 3600000 } };
const interaction_snap_l1: Pick<NonNullable<PresetStandardConfig["interaction"]>, "snap"> = { snap: { enabled: false } };
const interaction_snap_l2: Pick<NonNullable<PresetStandardConfig["interaction"]>, "snap"> = { snap: { unit: "day", rule: (base) => ({ snap: (t) => base.snap(t), step: (t, direction) => base.step(t, direction) }), alignToTasks: { tolerancePx: 12 }, pushSuccessors: true } };
const interaction_tooltip_l1: Pick<NonNullable<PresetStandardConfig["interaction"]>, "tooltip"> = { tooltip: { trigger: "hover", showDelay: 0, hideDelay: 0 } };
const interaction_tooltip_l2: Pick<NonNullable<PresetStandardConfig["interaction"]>, "tooltip"> = { tooltip: { content: (hit) => "OA tooltip", trigger: "both" } };
const interaction_contextMenu_l1: Pick<NonNullable<PresetStandardConfig["interaction"]>, "contextMenu"> = { contextMenu: { insertMode: "sibling" } };
const interaction_contextMenu_l2: Pick<NonNullable<PresetStandardConfig["interaction"]>, "contextMenu"> = { contextMenu: { items: (target) => [{ id: "oa-item", label: "OA item", run: () => {} }] } };
const interaction_zoomControls_l1: Pick<NonNullable<PresetStandardConfig["interaction"]>, "zoomControls"> = { zoomControls: { position: "top-left" } };
const interaction_zoomControls_l2: Pick<NonNullable<PresetStandardConfig["interaction"]>, "zoomControls"> = { zoomControls: { slider: false, zoomButtons: false, fitButton: false } };
const interaction_clipboard_l1: Pick<NonNullable<PresetStandardConfig["interaction"]>, "clipboard"> = { clipboard: { systemClipboard: false } };
const interaction_clipboard_l2: Pick<NonNullable<PresetStandardConfig["interaction"]>, "clipboard"> = { clipboard: { fields: ["name", "progress"] } };
const interaction_filterSearch_l1: Pick<NonNullable<PresetStandardConfig["interaction"]>, "filterSearch"> = { filterSearch: { searchBox: true } };
const interaction_filterSearch_l2: Pick<NonNullable<PresetStandardConfig["interaction"]>, "filterSearch"> = { filterSearch: { filterPanel: true, fields: [{ id: "oa-field", label: "OA Field", value: (task) => task.type ?? "task" }] } };
const interaction_editDialog_l1: Pick<NonNullable<PresetStandardConfig["interaction"]>, "editDialog"> = { editDialog: { openOnDoubleClick: false } };
const interaction_editDialog_l2: Pick<NonNullable<PresetStandardConfig["interaction"]>, "editDialog"> = { editDialog: { renderBody: (host, ctx) => { host.textContent = "OA dialog: " + ctx.task.name; } } };
const interaction_sidePanel_l1: Pick<NonNullable<PresetStandardConfig["interaction"]>, "sidePanel"> = { sidePanel: {} };
const interaction_sidePanel_l2: Pick<NonNullable<PresetStandardConfig["interaction"]>, "sidePanel"> = { sidePanel: { formatDate: (t) => new Date(t).toISOString().slice(0, 10) } };
const interaction_messages_l1: Pick<NonNullable<PresetStandardConfig["interaction"]>, "messages"> = { messages: {} };
const interaction_messages_l2: Pick<NonNullable<PresetStandardConfig["interaction"]>, "messages"> = { messages: { deleteConfirmTitle: (count) => "Delete " + count + " task(s)?" } };
const undo_redo_messages_l1: Pick<NonNullable<PresetStandardConfig["undoRedo"]>, "messages"> = { messages: {} };
const undo_redo_messages_l2: Pick<NonNullable<PresetStandardConfig["undoRedo"]>, "messages"> = { messages: { undone: "OA undone", redone: "" } };
const undo_redo_limit_l1: Pick<NonNullable<PresetStandardConfig["undoRedo"]>, "limit"> = { limit: 1 };
const undo_redo_limit_l2: Pick<NonNullable<PresetStandardConfig["undoRedo"]>, "limit"> = { limit: 1000 };
const undo_redo_keys_l1: Pick<NonNullable<PresetStandardConfig["undoRedo"]>, "keys"> = { keys: { undo: [], redo: [] } };
const undo_redo_keys_l2: Pick<NonNullable<PresetStandardConfig["undoRedo"]>, "keys"> = { keys: { undo: ["Ctrl+Alt+U"], redo: ["Ctrl+Alt+R"] } };
const portfolio_nodes_l1: Pick<PortfolioConfig, "nodes"> = { nodes: [] };
const portfolio_nodes_l2: Pick<PortfolioConfig, "nodes"> = { nodes: [{ id: "oa-init", kind: "initiative", name: "OA Initiative" }, { id: "oa-node", kind: "project", name: "OA Project", parentId: "oa-init", taskId: "oa-p" }] };
const portfolio_goals_l1: Pick<PortfolioConfig, "goals"> = { goals: [] };
const portfolio_goals_l2: Pick<PortfolioConfig, "goals"> = { goals: [{ id: "oa-goal", name: "OA Goal", taskIds: ["oa-a"], nodeIds: ["oa-node"], target: 0.5 }] };
const portfolio_views_l1: Pick<PortfolioConfig, "views"> = { views: {} };
const portfolio_views_l2: Pick<PortfolioConfig, "views"> = { views: { "oa-view": { nodeIds: ["oa-node"] } } };
const portfolio_dashboard_l1: Pick<PortfolioConfig, "dashboard"> = { dashboard: { open: true } };
const portfolio_dashboard_l2: Pick<PortfolioConfig, "dashboard"> = { dashboard: { open: true, widgets: ["summary", "status", "goals", "formulas"], formulas: [{ id: "oa-f1", label: "OA Task Count", evaluate: (tasks) => tasks.length }], groupOf: (task) => (task.type === "summary" ? "Summaries" : "Leaves"), renderWidget: (host, ctx) => { if (ctx.widget === "status") { var d = document.createElement("div"); d.textContent = "OA custom " + ctx.widget; host.appendChild(d); } } } };
const portfolio_messages_l1: Pick<PortfolioConfig, "messages"> = { messages: {} };
const portfolio_messages_l2: Pick<PortfolioConfig, "messages"> = { messages: { nodeName: (arg) => "OA " + arg.kind + " " + arg.ordinal } };
const resource_pool_l1: Pick<ResourceConfig, "pool"> = { pool: {} };
const resource_pool_l2: Pick<ResourceConfig, "pool"> = { pool: { resources: [{ id: "oa-r1", name: "OA Resource", kind: "person", capacity: 1, skills: ["dev"], costRate: 50 }, { id: "oa-r2", name: "OA Equipment", kind: "equipment", capacity: 0.5 }], bookings: [{ resourceId: "oa-r1", taskId: "oa-a", start: Date.UTC(2026, 7, 7), end: Date.UTC(2026, 7, 10), state: "confirmed", units: 0.5 }], syncToStore: true } };
const resource_assign_l1: Pick<ResourceConfig, "assign"> = { assign: {} };
const resource_assign_l2: Pick<ResourceConfig, "assign"> = { assign: { column: true, columnWidth: 220, dragReassign: false } };
const resource_view_l1: Pick<ResourceConfig, "view"> = { view: {} };
const resource_view_l2: Pick<ResourceConfig, "view"> = { view: { startOpen: true, resizable: false, teams: [{ name: "OA Team", members: ["oa-r1"] }], projectOf: (task) => (task.parentId ? "OA Project" : null) } };
const resource_utilization_l1: Pick<ResourceConfig, "utilization"> = { utilization: {} };
const resource_utilization_l2: Pick<ResourceConfig, "utilization"> = { utilization: { bucket: "week", weekStart: "sunday", threshold: 0.5, summaryPanel: true, role: (entry) => entry.kind, resourceLoad: (input) => input.allocated * 2 } };
const resource_loadChart_l1: Pick<ResourceConfig, "loadChart"> = { loadChart: {} };
const resource_loadChart_l2: Pick<ResourceConfig, "loadChart"> = { loadChart: { bucket: "week", total: true, lanes: true, axisLabels: true, valueLabels: true, laneScale: "shared", load: (input) => input.tasks.length, capacity: (input) => (input.resources.length || 1) } };
const resource_messages_l1: Pick<ResourceConfig, "messages"> = { messages: {} };
const resource_messages_l2: Pick<ResourceConfig, "messages"> = { messages: { assignColumnHeader: "OA Resources" } };
const scheduling_dependencies_l1: Pick<NonNullable<PresetStandardConfig["scheduling"]>, "dependencies"> = { dependencies: { routingStyle: "straight", linkStyle: { width: 2, arrowHead: "open" }, linkEditing: true, highlightPaths: true } };
const scheduling_dependencies_l2: Pick<NonNullable<PresetStandardConfig["scheduling"]>, "dependencies"> = { dependencies: { showLinks: false, allowLinkCreate: false } };
const scheduling_autoSchedule_l1: Pick<NonNullable<PresetStandardConfig["scheduling"]>, "autoSchedule"> = { autoSchedule: { enabled: true } };
const scheduling_autoSchedule_l2: Pick<NonNullable<PresetStandardConfig["scheduling"]>, "autoSchedule"> = { autoSchedule: { modeColumn: true } };
const scheduling_calendars_l1: Pick<NonNullable<PresetStandardConfig["scheduling"]>, "calendars"> = { calendars: {} };
const scheduling_calendars_l2: Pick<NonNullable<PresetStandardConfig["scheduling"]>, "calendars"> = { calendars: { calendars: [{ id: "oa-cal", name: "OA Calendar", workingDays: [1, 2, 3, 4, 5], isDefault: true }], editor: true } };
const scheduling_criticalPath_l1: Pick<NonNullable<PresetStandardConfig["scheduling"]>, "criticalPath"> = { criticalPath: {} };
const scheduling_criticalPath_l2: Pick<NonNullable<PresetStandardConfig["scheduling"]>, "criticalPath"> = { criticalPath: { thresholdDays: 1, nearCriticalDays: 2, showFloat: true, criticalColor: "#7c3aed" } };
const scheduling_diagnostics_l1: Pick<NonNullable<PresetStandardConfig["scheduling"]>, "diagnostics"> = { diagnostics: { panel: true } };
const scheduling_diagnostics_l2: Pick<NonNullable<PresetStandardConfig["scheduling"]>, "diagnostics"> = { diagnostics: { panel: false } };
const scheduling_messages_l1: Pick<NonNullable<PresetStandardConfig["scheduling"]>, "messages"> = { messages: {} };
const scheduling_messages_l2: Pick<NonNullable<PresetStandardConfig["scheduling"]>, "messages"> = { messages: { modeColumnHeader: "OA Mode" } };
const tracking_baselines_l1: Pick<TrackingConfig, "baselines"> = { baselines: {} };
const tracking_baselines_l2: Pick<TrackingConfig, "baselines"> = { baselines: { baselines: [{ id: "oa-bl", name: "OA Baseline", tasks: [{ id: "oa-a", start: Date.UTC(2026, 7, 6, 12), end: Date.UTC(2026, 7, 10, 12) }, { id: "oa-b", start: Date.UTC(2026, 7, 11, 12), end: Date.UTC(2026, 7, 16, 12) }] }], active: "oa-bl", barStyle: "overlay", slipThresholdMs: 0, criticalPath: true } };
const tracking_progress_l1: Pick<TrackingConfig, "progress"> = { progress: {} };
const tracking_progress_l2: Pick<TrackingConfig, "progress"> = { progress: { statusDate: Date.UTC(2026, 7, 9), progressLine: true, colorBars: true, progressWeighting: "duration", snapshots: [{ date: Date.UTC(2026, 7, 5), percentComplete: 10, completedCount: 0, lateCount: 0, taskCount: 2 }, { date: Date.UTC(2026, 7, 6), percentComplete: 25, completedCount: 0, lateCount: 1, taskCount: 2 }] } };
const tracking_cost_l1: Pick<TrackingConfig, "cost"> = { cost: {} };
const tracking_cost_l2: Pick<TrackingConfig, "cost"> = { cost: { rates: [{ resourceId: "oa-r1", standard: 40, overtime: 60 }], hoursPerDay: 6, budget: 5000, budgets: { general: 2000 }, alertThreshold: 0.5, statusDate: Date.UTC(2026, 7, 9), formulas: [{ id: "oa-cf", label: "OA Row Count", evaluate: (input) => input.rows.length }] } };
const tracking_evm_l1: Pick<TrackingConfig, "evm"> = { evm: {} };
const tracking_evm_l2: Pick<TrackingConfig, "evm"> = { evm: { method: "fiftyFifty", eacMethod: "remaining", statusDate: Date.UTC(2026, 7, 9), projectBac: 3000, snapshots: [{ t: Date.UTC(2026, 7, 5), ev: 200, ac: 250 }], formulas: [{ id: "oa-ef", label: "OA Curve Points", evaluate: (input) => input.curve.length }] } };
const tracking_messages_l1: Pick<TrackingConfig, "messages"> = { messages: {} };
const tracking_messages_l2: Pick<TrackingConfig, "messages"> = { messages: { baselineName: (ordinal) => "OA Baseline " + ordinal } };
